import type { MenuItemRow, SiteSettingsRow } from "@/types/menu";

const id = (section: string, i: number) => `fb-${section}-${i}`;

export const FALLBACK_SITE_SETTINGS: SiteSettingsRow = {
  id: 1,
  ticker_segments: [
    "New & Seasonal Flavors",
    "35+ Artisan Gelato Flavors",
    "Italian Coffee",
    "Frozen Yogurt",
    "160+ Locations Worldwide",
  ],
  seasonal_tagline: "Spring 2026 Arrivals",
  hero_eyebrow: "Tarzana · Los Angeles",
  hero_video_url: null,
  hero_video_poster_url: null,
  separator_video_url: null,
  hero_secondary_label: null,
  hero_secondary_href: null,
  pastry_sec_the: "Just in",
  pastry_sec_big_line1: "New",
  pastry_sec_big_line2: "Products",
  pastry_sec_tag: "Pastries · Baked goods · Rotating picks",
};

/** Shown when Supabase has no `pastries` rows yet (until owner adds real items). */
export const DEFAULT_NEW_PRODUCT_ITEMS: MenuItemRow[] = [
  ["🥐", "Butter Croissant", "Flaky layers, baked fresh each morning.", "$4.50"],
  ["🍫", "Pain au Chocolat", "Classic chocolate-filled viennoiserie.", "$5.00"],
  ["🫐", "Berry Danish", "Seasonal fruit and cream cheese.", "$5.50"],
  ["🧁", "Cinnamon Morning Bun", "Soft bun with cinnamon swirl and light glaze.", "$5.25"],
  ["🥖", "Ham & Cheese Croissant", "Savory croissant with ham and Swiss.", "$6.50"],
].map(([emoji, name, desc, price], i) => ({
  id: id("pastries", i),
  section: "pastries" as const,
  name: name as string,
  description: desc as string,
  price_display: price as string,
  emoji: emoji as string,
  image_url: null,
  tags: [],
  badge: null,
  is_new: i === 0 || i === 3,
  is_fave: false,
  is_vegan: false,
  sort_order: i,
  is_active: true,
  promo_label: null,
  seasonal_ribbon_label: null,
}));

/** Append sample New products when DB section is empty (IDs are synthetic — replace via admin). */
export function withDefaultNewProductsIfEmpty(items: MenuItemRow[]): MenuItemRow[] {
  if (items.some((r) => r.section === "pastries")) return items;
  return [...items, ...DEFAULT_NEW_PRODUCT_ITEMS];
}

function gelatoTags(name: string, desc: string): string[] {
  const t = `${name} ${desc}`.toLowerCase();
  const tags: string[] = [];
  if (/chocolate|choc|hazelnut|nougat|bueno|stracciatella|black forest/.test(t))
    tags.push("choc");
  if (/pistachio|hazelnut|macadamia|cashew|almond/.test(t)) tags.push("nut");
  if (
    /strawberry|berry|mango|tropical|lemon|raspberry|cherry|passion|watermelon/.test(
      t
    )
  )
    tags.push("fruit");
  return tags;
}

export const FALLBACK_MENU_ITEMS: MenuItemRow[] = [
  {
    id: id("seasonal", 0),
    section: "seasonal",
    name: "Pavlova & Mixed Berries",
    description: "Spring 2026 arrival — meringue with fresh berries.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 0,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 1),
    section: "seasonal",
    name: "Macadamia",
    description: "New arrival — buttery macadamia with caramel.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 1,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 2),
    section: "seasonal",
    name: "Pistachio",
    description: "Our most loved flavor. 100% pure Sicilian paste.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: true,
    is_vegan: false,
    sort_order: 2,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 3),
    section: "seasonal",
    name: "Black Forest",
    description: "Dark chocolate with cherry compote and cream.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 3,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 4),
    section: "seasonal",
    name: "Watermelon Mint",
    description: "Fresh watermelon sorbet with mint. Summer special.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Limited",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 4,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  ...[
    ["Pistachio", "100% pure Sicilian pistachio paste. No artificial color ever."],
    ["Hazelnut Mousse & Crunch Choc", "Rich hazelnut mousse with layers of crunch chocolate."],
    ["Vanilla Madagascar", "Premium Madagascar vanilla bean. Pure and aromatic."],
    ["Cookieman", "Biscuit-based gelato with chocolate and meringue pieces."],
    ["Salted Caramel", "Buttery caramel with a touch of sea salt."],
  ].map(([name, desc], i) => ({
    id: id("bestsellers", i),
    section: "bestsellers" as const,
    name,
    description: desc,
    price_display: "from $7",
    emoji: null,
    image_url: null,
    tags: gelatoTags(name, desc),
    badge: null,
    is_new: false,
    is_fave: true,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...[
    {
      n: "Pistachio",
      d: "100% pure Sicilian pistachio paste. No artificial color ever.",
      new: false,
      fave: true,
    },
    {
      n: "Hazelnut Mousse & Crunch Choc",
      d: "Rich hazelnut mousse with layers of crunch chocolate.",
      new: false,
      fave: true,
    },
    {
      n: "Pavlova & Mixed Berries",
      d: "Meringue cream with a fresh mixed berry compote.",
      new: true,
      fave: false,
    },
    {
      n: "Belgian Chocolate",
      d: "Deep, rich Belgian dark chocolate — intensely smooth.",
      new: false,
      fave: false,
    },
    {
      n: "White Choc & Pistachio",
      d: "White chocolate cream swirled with pistachio paste.",
      new: false,
      fave: false,
    },
    {
      n: "Nougat Wafers",
      d: "Creamy nougat studded with crispy wafer layers.",
      new: false,
      fave: false,
    },
    {
      n: "Choc Almonds & Caramel",
      d: "Dark chocolate with toasted almonds and salted caramel.",
      new: false,
      fave: false,
    },
    {
      n: "Bueno Cream",
      d: "Kinder Bueno inspired — hazelnut cream with wafer pieces.",
      new: false,
      fave: false,
    },
    {
      n: "Vanilla Madagascar",
      d: "Premium Madagascar vanilla bean. Pure and aromatic.",
      new: false,
      fave: true,
    },
    {
      n: "Choc with Pistachio & Kadaif",
      d: "Chocolate gelato with pistachio and crispy kadaif pastry.",
      new: false,
      fave: false,
    },
    {
      n: "Cookieman",
      d: "Biscuit-based gelato with chocolate and meringue pieces.",
      new: false,
      fave: true,
    },
    {
      n: "Salted Caramel",
      d: "Buttery caramel with a touch of sea salt.",
      new: false,
      fave: true,
    },
    {
      n: "Cheesecake Caramel Cookies",
      d: "New York cheesecake gelato with caramel cookie crumble.",
      new: false,
      fave: false,
    },
    {
      n: "White Choc Pretzels",
      d: "White chocolate with salty pretzel pieces — sweet meets salty.",
      new: false,
      fave: false,
    },
    {
      n: "Chocolate Mint",
      d: "Dark chocolate with a refreshing fresh mint finish.",
      new: false,
      fave: false,
    },
    {
      n: "White Choc & Cookies",
      d: "White chocolate base loaded with Oreo cookie pieces.",
      new: false,
      fave: false,
    },
    {
      n: "Mascarpone & Strawberry",
      d: "Silky mascarpone ricotta cream with fresh strawberry.",
      new: false,
      fave: false,
    },
    {
      n: "Coffee Stracciatella",
      d: "Italian espresso gelato with dark chocolate chip shards.",
      new: false,
      fave: false,
    },
    {
      n: "Hazelnut & Choc Cream",
      d: "Double hazelnut and milk chocolate. Pure indulgence.",
      new: false,
      fave: false,
    },
    {
      n: "Macadamia",
      d: "Buttery macadamia nut with a smooth caramel base.",
      new: true,
      fave: false,
    },
    {
      n: "Biscuit Cheesecake",
      d: "Cheesecake gelato on a buttery biscuit crumble base.",
      new: false,
      fave: false,
    },
    {
      n: "Tropical",
      d: "Mango, passion fruit, and coconut cream blended together.",
      new: false,
      fave: false,
    },
    {
      n: "Black Forest",
      d: "Dark chocolate with cherry compote and cream.",
      new: false,
      fave: false,
    },
    {
      n: "Salted Cashew",
      d: "Roasted cashew gelato with a salted caramel swirl.",
      new: false,
      fave: false,
    },
    {
      n: "Stracciatella",
      d: "Pure cream gelato with dark chocolate shards. The Italian classic.",
      new: false,
      fave: false,
    },
  ].map((row, i) => ({
    id: id("gelato", i),
    section: "gelato" as const,
    name: row.n,
    description: row.d,
    price_display: "from $7",
    emoji: null,
    image_url: null,
    tags: [...gelatoTags(row.n, row.d), ...(row.new ? ["new"] : [])],
    badge: null,
    is_new: row.new,
    is_fave: row.fave,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...[
    { n: "VEGAN — Strawberry", d: "Fresh strawberry sorbet. Dairy-free.", new: false },
    { n: "VEGAN — Coconut", d: "Creamy coconut sorbet with tropical notes.", new: false },
    { n: "VEGAN — Mango", d: "Sun-ripened mango sorbet. Pure and refreshing.", new: false },
    {
      n: "VEGAN — Tropical",
      d: "Mango, passion fruit and coconut in one scoop.",
      new: false,
    },
    {
      n: "VEGAN — Dark Chocolate",
      d: "70% dark chocolate sorbet. Intense and completely vegan.",
      new: false,
    },
    {
      n: "VEGAN — Limoncello",
      d: "Amalfi Coast lemon with a limoncello kick.",
      new: false,
    },
    {
      n: "VEGAN — Watermelon Mint",
      d: "Fresh watermelon with a cool mint finish.",
      new: true,
    },
    {
      n: "VEGAN — Banana Date",
      d: "Caramelized banana with Medjool date sweetness.",
      new: false,
    },
    {
      n: "VEGAN — Cookie",
      d: "Vegan biscuit and chocolate chip gelato.",
      new: false,
    },
  ].map((row, i) => ({
    id: id("sorbet", i),
    section: "sorbet" as const,
    name: row.n,
    description: row.d,
    price_display: "from $7",
    emoji: null,
    image_url: null,
    tags: gelatoTags(row.n, row.d),
    badge: null,
    is_new: row.new,
    is_fave: false,
    is_vegan: true,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...DEFAULT_NEW_PRODUCT_ITEMS,
  ...[
    ["☕", "Espresso", "Pure Italian single or double shot. Intense, smooth, no bitterness.", "$3.50"],
    ["☕", "Cappuccino", "Espresso with perfectly steamed microfoam. The Italian classic.", "$5.00"],
    ["☕", "Latte", "Smooth espresso with velvety steamed milk. Hot or iced.", "$5.50"],
    ["☕", "Americano", "Espresso pulled long with hot water. Bold and clean.", "$4.00"],
    ["🧊", "Iced Coffee", "Our Italian blend over ice. Refreshing and rich.", "$5.00"],
    ["🫧", "Affogato", "Vanilla gelato drowned in a hot espresso shot. The ultimate combo.", "$7.00"],
    ["☕", "Macchiato", "Espresso marked with just a touch of foamed milk.", "$4.50"],
    ["🧊", "Cold Brew", "Slow-steeped 18 hours. Smooth, low-acid, perfect on a hot day.", "$5.50"],
  ].map(([emoji, name, desc, price], i) => ({
    id: id("coffee", i),
    section: "coffee" as const,
    name: name as string,
    description: desc as string,
    price_display: price as string,
    emoji: emoji as string,
    image_url: null,
    tags: [],
    badge: null,
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...[
    ["🫧", "Italian Sparkling Water", "San Pellegrino — the perfect palate cleanser.", "$3.00"],
    ["💧", "Still Water", "Acqua Panna natural mineral water.", "$2.50"],
    ["🥤", "Italian Soda", "Sparkling water with Italian syrup of your choice.", "$4.00"],
    ["🍋", "Fresh Lemonade", "Squeezed fresh with a hint of mint.", "$4.50"],
  ].map(([emoji, name, desc, price], i) => ({
    id: id("drinks", i),
    section: "drinks" as const,
    name: name as string,
    description: desc as string,
    price_display: price as string,
    emoji: emoji as string,
    image_url: null,
    tags: [],
    badge: null,
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
];
