import type { MenuItemRow, SiteSettingsRow } from "@/types/menu";

const id = (section: string, i: number) => `fb-${section}-${i}`;

export const FALLBACK_SITE_SETTINGS: SiteSettingsRow = {
  id: 1,
  ticker_segments: [
    "New & Seasonal Flavors",
    "35+ Artisan Gelato Flavors",
    "Italian Coffee",
    "Frozen Yogurt",
    "160+ Locations Worldwide",
  ],
  seasonal_tagline: "Spring 2026 Arrivals",
  hero_eyebrow: "Tarzana · Los Angeles",
  hero_video_url: null,
  hero_video_poster_url: null,
  hero_bg_image_url: null,
  separator_video_url: null,
  hero_secondary_label: null,
  hero_secondary_href: null,
  pastry_sec_the: "Just in",
  pastry_sec_big_line1: "New",
  pastry_sec_big_line2: "Products",
  pastry_sec_tag: "Pastries · Baked goods · Rotating picks",
  section_labels: null,
};

/** Shown when Supabase has no `pastries` rows yet (until owner adds real items). */
export const DEFAULT_NEW_PRODUCT_ITEMS: MenuItemRow[] = [
  ["🥐", "Butter Croissant", "Flaky layers, baked fresh each morning.", "$4.50"],
  ["🍫", "Pain au Chocolat", "Classic chocolate-filled viennoiserie.", "$5.00"],
  ["🫐", "Berry Danish", "Seasonal fruit and cream cheese.", "$5.50"],
  ["🧁", "Cinnamon Morning Bun", "Soft bun with cinnamon swirl and light glaze.", "$5.25"],
  ["🥖", "Ham & Cheese Croissant", "Savory croissant with ham and Swiss.", "$6.50"],
].map(([emoji, name, desc, price], i) => ({
  id: id("pastries", i),
  section: "pastries" as const,
  name: name as string,
  description: desc as string,
  price_display: price as string,
  emoji: emoji as string,
  image_url: null,
  tags: [],
  badge: null,
  is_new: i === 0 || i === 3,
  is_fave: false,
  is_vegan: false,
  sort_order: i,
  is_active: true,
  promo_label: null,
  seasonal_ribbon_label: null,
}));

/** Append sample New products when DB section is empty (IDs are synthetic — replace via admin). */
export function withDefaultNewProductsIfEmpty(items: MenuItemRow[]): MenuItemRow[] {
  if (items.some((r) => r.section === "pastries")) return items;
  return [...items, ...DEFAULT_NEW_PRODUCT_ITEMS];
}

/** Default frozen yogurt rows when Supabase has no `yogurt` section yet (matches seed.sql). */
export const DEFAULT_YOGURT_ITEMS: MenuItemRow[] = [
  {
    id: id("yogurt", 0),
    section: "yogurt" as const,
    name: "Plain Tart",
    description: "Classic tart frozen yogurt — bright, tangy, and refreshing.",
    price_display: "from $5",
    emoji: null,
    image_url: null,
    tags: [],
    badge: null,
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 0,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("yogurt", 1),
    section: "yogurt" as const,
    name: "Vanilla Soft Serve",
    description: "Creamy Madagascar vanilla soft serve.",
    price_display: "from $5",
    emoji: null,
    image_url: null,
    tags: [],
    badge: null,
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 1,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
];

export function withDefaultYogurtIfEmpty(items: MenuItemRow[]): MenuItemRow[] {
  if (items.some((r) => r.section === "yogurt")) return items;
  return [...items, ...DEFAULT_YOGURT_ITEMS];
}

/** Pastries + yogurt starter rows when those sections have no DB rows yet. */
export function withMenuSectionDefaults(items: MenuItemRow[]): MenuItemRow[] {
  return withDefaultYogurtIfEmpty(withDefaultNewProductsIfEmpty(items));
}

function gelatoTags(name: string, desc: string): string[] {
  const t = `${name} ${desc}`.toLowerCase();
  const tags: string[] = [];
  if (/chocolate|choc|hazelnut|nougat|bueno|stracciatella|black forest/.test(t))
    tags.push("choc");
  if (/pistachio|hazelnut|macadamia|cashew|almond/.test(t)) tags.push("nut");
  if (
    /strawberry|berry|mango|tropical|lemon|raspberry|cherry|passion|watermelon/.test(
      t
    )
  )
    tags.push("fruit");
  return tags;
}

export const FALLBACK_MENU_ITEMS: MenuItemRow[] = [
  {
    id: id("seasonal", 0),
    section: "seasonal",
    name: "Pavlova & Mixed Berries",
    description: "Cream-base with mixed berries & meringues.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 0,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 1),
    section: "seasonal",
    name: "Macadamia Cream",
    description: "Macadamia flavored gelato with macadamia cream & caramelized macadamia nuts.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 1,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 2),
    section: "seasonal",
    name: "Pistachio",
    description: "A blend of real pistachios.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: true,
    is_vegan: false,
    sort_order: 2,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 3),
    section: "seasonal",
    name: "Black Forest",
    description:
      "Caramelised hazelnuts and rum flavored gelato with mixed berries jam and hazelnut chocolate cream.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Seasonal",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 3,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  {
    id: id("seasonal", 4),
    section: "seasonal",
    name: "Watermelon & Fresh Mint",
    description: "Fragrant mint and watermelon sorbet.",
    price_display: null,
    emoji: null,
    image_url: null,
    tags: [],
    badge: "Limited",
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: 4,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  },
  ...[
    ["Pistachio", "A blend of real pistachios."],
    ["Hazelnut Mousse & Chocolate Crunch", "Hazelnut flavored gelato with chocolate cream, wafers, and roasted hazelnut."],
    ["Vanilla", "Vanilla flavored gelato with real vanilla beans."],
    ["Cookieman", "Biscuit base with hazelnut chocolate & meringues."],
    ["Salted Caramel", "Caramel flavored gelato with salt and toffee cream."],
  ].map(([name, desc], i) => ({
    id: id("bestsellers", i),
    section: "bestsellers" as const,
    name,
    description: desc,
    price_display: "from $7",
    emoji: null,
    image_url: null,
    tags: gelatoTags(name, desc),
    badge: null,
    is_new: false,
    is_fave: true,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...[
    {
      n: "Pistachio",
      d: "A blend of real pistachios.",
      new: false,
      fave: true,
    },
    {
      n: "Chocolate",
      d: "Luxurious milk chocolate.",
      new: false,
      fave: false,
    },
    {
      n: "Black Forest",
      d: "Caramelised hazelnuts and rum flavored gelato with mixed berries jam and hazelnut chocolate cream.",
      new: false,
      fave: false,
    },
    {
      n: "Strawberry",
      d: "A fruity strawberry indulgence.",
      new: false,
      fave: false,
    },
    {
      n: "Cookieman",
      d: "Biscuit base with hazelnut chocolate & meringues.",
      new: false,
      fave: true,
    },
    {
      n: "Mango",
      d: "Made with fresh mango.",
      new: false,
      fave: false,
    },
    {
      n: "Pavlova & Mixed Berries",
      d: "Cream-base with mixed berries & meringues.",
      new: true,
      fave: false,
    },
    {
      n: "Macadamia Cream",
      d: "Macadamia flavored gelato with macadamia cream & caramelized macadamia nuts.",
      new: true,
      fave: false,
    },
    {
      n: "Chocolate & Hazelnut",
      d: "Hazelnut flavored gelato with milk chocolate cream and roasted hazelnut.",
      new: false,
      fave: false,
    },
    {
      n: "Chocolate Caramel and Almonds",
      d: "Caramel flavored gelato with chocolate cream and roasted almonds.",
      new: false,
      fave: false,
    },
    {
      n: "Milk Chocolate Pretzel",
      d: "Milk chocolate flavored gelato with pretzel sauce.",
      new: false,
      fave: false,
    },
    {
      n: "White Chocolate & Cookies",
      d: "White chocolate flavored gelato with cookie crumbs.",
      new: false,
      fave: false,
    },
    {
      n: "Nougat Wafer",
      d: "Hazelnut flavored gelato with wafers.",
      new: false,
      fave: false,
    },
    {
      n: "White Chocolate & Nougat Wafers",
      d: "White chocolate flavored gelato with chocolate and hazelnut cream, hazelnuts and wafers.",
      new: false,
      fave: false,
    },
    {
      n: "Vanilla",
      d: "Vanilla flavored gelato with real vanilla beans.",
      new: false,
      fave: true,
    },
    {
      n: "White Chocolate & Pistachio Cream",
      d: "White chocolate flavored gelato with pistachio cream and pieces of roasted pistachios.",
      new: false,
      fave: false,
    },
    {
      n: "Salted Cashew",
      d: "Salted cashew flavored gelato with cashew varigato.",
      new: false,
      fave: false,
    },
    {
      n: "Mint Chocolate",
      d: "Mint flavored gelato with milk chocolate cream and dark chocolate chips.",
      new: false,
      fave: false,
    },
    {
      n: "Strawberry Mascarpone & Ricotta",
      d: "Mascarpone cheese flavored gelato with strawberry jam and white chocolate cream.",
      new: false,
      fave: false,
    },
    {
      n: "Cheesecake Caramel Cookies",
      d: "Cheesecake flavored gelato with caramel cream and pieces of caramel cookies.",
      new: false,
      fave: false,
    },
    {
      n: "Chocolate Nut Cream",
      d: "Hazelnut flavored gelato with milk chocolate cream and roasted hazelnuts.",
      new: false,
      fave: false,
    },
    {
      n: "Crème Brulee Pistachio Crumble",
      d: "Crème brulee flavored gelato with pistachio crumble and varigato.",
      new: true,
      fave: false,
    },
    {
      n: "Hazelnut Mousse & Chocolate Crunch",
      d: "Hazelnut flavored gelato with chocolate cream, wafers, and roasted hazelnut.",
      new: false,
      fave: true,
    },
    {
      n: "White Chocolate Espresso",
      d: "Coffee flavored gelato with white chocolate cream and dark chocolate chips.",
      new: false,
      fave: false,
    },
    {
      n: "Salted Caramel",
      d: "Caramel flavored gelato with salt and toffee cream.",
      new: false,
      fave: true,
    },
    {
      n: "Biscuit Cake",
      d: "Cheesecake flavored gelato with biscuit cream and chocolate chips.",
      new: false,
      fave: false,
    },
    {
      n: "Vegan Cookie & Cream",
      d: "Chocolate cookie flavored gelato with chocolate cookie cream and cookie crumbs.",
      new: false,
      fave: false,
    },
    {
      n: "No Sugar Added Coffee",
      d: "A guilt-free pick-me-up.",
      new: false,
      fave: false,
    },
  ].map((row, i) => ({
    id: id("gelato", i),
    section: "gelato" as const,
    name: row.n,
    description: row.d,
    price_display: "from $7",
    emoji: null,
    image_url: null,
    tags: [...gelatoTags(row.n, row.d), ...(row.new ? ["new"] : [])],
    badge: null,
    is_new: row.new,
    is_fave: row.fave,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...[
    {
      n: "Coconut Sorbet",
      d: "Sorbet based on coconut milk and coconut pieces.",
      new: false,
    },
    { n: "Limoncello", d: "Mint and lemon sorbet.", new: false },
    {
      n: "Watermelon & Fresh Mint",
      d: "Fragrant mint and watermelon sorbet.",
      new: true,
    },
    {
      n: "Dark Chocolate",
      d: "Dark chocolate sorbet based on 40% cocoa butter.",
      new: false,
    },
  ].map((row, i) => ({
    id: id("sorbet", i),
    section: "sorbet" as const,
    name: row.n,
    description: row.d,
    price_display: "from $7",
    emoji: null,
    image_url: null,
    tags: gelatoTags(row.n, row.d),
    badge: null,
    is_new: row.new,
    is_fave: false,
    is_vegan: true,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...DEFAULT_NEW_PRODUCT_ITEMS,
  ...[
    ["☕", "Espresso", "Pure Italian single or double shot. Intense, smooth, no bitterness.", "$3.50"],
    ["☕", "Cappuccino", "Espresso with perfectly steamed microfoam. The Italian classic.", "$5.00"],
    ["☕", "Latte", "Smooth espresso with velvety steamed milk. Hot or iced.", "$5.50"],
    ["☕", "Americano", "Espresso pulled long with hot water. Bold and clean.", "$4.00"],
    ["🧊", "Iced Coffee", "Our Italian blend over ice. Refreshing and rich.", "$5.00"],
    ["🫧", "Affogato", "Vanilla gelato drowned in a hot espresso shot. The ultimate combo.", "$7.00"],
    ["☕", "Macchiato", "Espresso marked with just a touch of foamed milk.", "$4.50"],
    ["🧊", "Cold Brew", "Slow-steeped 18 hours. Smooth, low-acid, perfect on a hot day.", "$5.50"],
  ].map(([emoji, name, desc, price], i) => ({
    id: id("coffee", i),
    section: "coffee" as const,
    name: name as string,
    description: desc as string,
    price_display: price as string,
    emoji: emoji as string,
    image_url: null,
    tags: [],
    badge: null,
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...[
    ["🫧", "Italian Sparkling Water", "San Pellegrino — the perfect palate cleanser.", "$3.00"],
    ["💧", "Still Water", "Acqua Panna natural mineral water.", "$2.50"],
    ["🥤", "Italian Soda", "Sparkling water with Italian syrup of your choice.", "$4.00"],
    ["🍋", "Fresh Lemonade", "Squeezed fresh with a hint of mint.", "$4.50"],
  ].map(([emoji, name, desc, price], i) => ({
    id: id("drinks", i),
    section: "drinks" as const,
    name: name as string,
    description: desc as string,
    price_display: price as string,
    emoji: emoji as string,
    image_url: null,
    tags: [],
    badge: null,
    is_new: false,
    is_fave: false,
    is_vegan: false,
    sort_order: i,
    is_active: true,
    promo_label: null,
    seasonal_ribbon_label: null,
  })),
  ...DEFAULT_YOGURT_ITEMS,
];
